### ISSUE TITLE
Excess curly braces

### ISSUE THREAD

**Issue by KamenDimitrov97** [hubs-community/mozilla-hubs-ce-chart#8]
# Description
There's an excess curly brace on line 9 in the `charts/haproxy/templates/clusterrole.yaml`
There's an excess curly brace on line 32,34,35 in the `charts/reticulum/templates/persistentvolume.yaml`

This issue may lead to syntax errors in the creation of the clusterrole and pvs 
example in clusterrole:
```
  verbs:
  - get
  - list
  - watch}
```
which removes the last verb.

**Comment by Doginal** [comment]
Thanks!

**Comment by Doginal** [comment]
merged #9
